module.exports = {
    apps:[
        {
            name: "SpotWssBinance",
            cmd: "/root/WssMiddleware",
            script: "/root/WssMiddleware/App/public/binance_wss.py",
            interpreter: "/root/miniconda3/envs/CexMM/bin/python",
            args: "",
            namespace: "SpotWss",
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: "400M",
            out_file: "/root/WssMiddleware/logs/pm2/SpotWssBinance.out.log",
            error_file: "/root/WssMiddleware/logs/pm2/SpotWssBinance.error.log",
            log_date_format: "YYYY-MM-DD HH:mm:ss",
            ignore_watch: "/root/WssMiddleware/logs",
            min_uptime: "60s",
            max_restarts: 30,
            env: {
            NODE_ENV: "development",
            },
            env_production: {
            NODE_ENV: "production",
            },
        },
        // {
        //     name: "SpotWssGate",
        //     cmd: "/root/WssMiddleware",
        //     script: "/root/WssMiddleware/App/public/gate_wss.py",
        //     interpreter: "/root/miniconda3/envs/CexMM/bin/python",
        //     args: "",
        //     namespace: "SpotWss",
        //     instances: 1,
        //     autorestart: true,
        //     watch: false,
        //     max_memory_restart: "400M",
        //     out_file: "/root/WssMiddleware/logs/pm2/SpotWssGate.out.log",
        //     error_file: "/root/WssMiddleware/logs/pm2/SpotWssGate.error.log",
        //     log_date_format: "YYYY-MM-DD HH:mm:ss",
        //     ignore_watch: "/root/WssMiddleware/logs",
        //     min_uptime: "60s",
        //     max_restarts: 30,
        //     env: {
        //     NODE_ENV: "development",
        //     },
        //     env_production: {
        //     NODE_ENV: "production",
        //     },
        // },
        // {
        //     name: "SpotWssOkex",
        //     cmd: "/root/WssMiddleware",
        //     script: "/root/WssMiddleware/App/public/okex_wss.py",
        //     interpreter: "/root/miniconda3/envs/CexMM/bin/python",
        //     args: "",
        //     namespace: "SpotWss",
        //     instances: 1,
        //     autorestart: true,
        //     watch: false,
        //     max_memory_restart: "400M",
        //     out_file: "/root/WssMiddleware/logs/pm2/SpotWssOkex.out.log",
        //     error_file: "/root/WssMiddleware/logs/pm2/SpotWssOkex.error.log",
        //     log_date_format: "YYYY-MM-DD HH:mm:ss",
        //     ignore_watch: "/root/WssMiddleware/logs",
        //     min_uptime: "60s",
        //     max_restarts: 30,
        //     env: {
        //     NODE_ENV: "development",
        //     },
        //     env_production: {
        //     NODE_ENV: "production",
        //     },
        // },
        // {
        //     name: "SpotWssLbk",
        //     cmd: "/root/WssMiddleware",
        //     script: "/root/WssMiddleware/App/public/lbk_wss.py",
        //     interpreter: "/root/miniconda3/envs/CexMM/bin/python",
        //     args: "",
        //     namespace: "SpotWss",
        //     instances: 1,
        //     autorestart: true,
        //     watch: false,
        //     max_memory_restart: "400M",
        //     out_file: "/root/WssMiddleware/logs/pm2/SpotWssLbk.out.log",
        //     error_file: "/root/WssMiddleware/logs/pm2/SpotWssLbk.error.log",
        //     log_date_format: "YYYY-MM-DD HH:mm:ss",
        //     ignore_watch: "/root/WssMiddleware/logs",
        //     min_uptime: "60s",
        //     max_restarts: 30,
        //     env: {
        //     NODE_ENV: "development",
        //     },
        //     env_production: {
        //     NODE_ENV: "production",
        //     },
        // },
    ]
}
