const base = {
    cwd: "/root/WssMiddlewareV2/",
    interpreter: "/root/anaconda3/envs/CexMM/bin/python",
    namespace: "SpotWssV2",
    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: "200M",
    log_date_format: "YYYY-MM-DD HH:mm:ss",
    ignore_watch: "/root/WssMiddlewareV2/logs",
    min_uptime: "60s",
    max_restarts: 30,
    env: {
      NODE_ENV: "development",
    },
    env_production: {
      NODE_ENV: "production",
    },
};
module.exports = {
    apps:[
        // binance
        {
            name: "SpotWssBinanceV2-DEPTH",
            script: "App/public/binance_wss.py",
            args: "--channel=depth",
            out_file: "/root/WssMiddlewareV2/logs/SpotWssBinance.out.log",
            error_file: "/root/WssMiddlewareV2/logs/SpotWssBinance.error.log",
            ...base,
        },
        {
            name: "SpotWssBinanceV2-KLINE",
            script: "App/public/binance_wss.py",
            args: "--channel=kline",
            out_file: "/root/WssMiddlewareV2/logs/SpotWssBinance.out.log",
            error_file: "/root/WssMiddlewareV2/logs/SpotWssBinance.error.log",
            ...base,
        },
        {
            name: "SpotWssBinanceV2-TRADE",
            script: "App/public/binance_wss.py",
            args: "--channel=trade",
            out_file: "/root/WssMiddlewareV2/logs/SpotWssBinance.out.log",
            error_file: "/root/WssMiddlewareV2/logs/SpotWssBinance.error.log",
            ...base,
        },
        {
            name: "SpotWssBinanceV2-TICKER",
            script: "App/public/binance_wss.py",
            args: "--channel=ticker",
            out_file: "/root/WssMiddlewareV2/logs/SpotWssBinance.out.log",
            error_file: "/root/WssMiddlewareV2/logs/SpotWssBinance.error.log",
            ...base,
        },
        // gate
        {
            name: "SpotWssGateV2-DEPTH",
            script: "App/public/gate_wss.py",
            args: "--channel=depth",
            out_file: "/root/WssMiddlewareV2/logs/SpotWssGate.out.log",
            error_file: "/root/WssMiddlewareV2/logs/SpotWssGate.error.log",
            ...base,
        },
        {
            name: "SpotWssGateV2-KLINE",
            script: "App/public/gate_wss.py",
            args: "--channel=kline",
            out_file: "/root/WssMiddlewareV2/logs/SpotWssGate.out.log",
            error_file: "/root/WssMiddlewareV2/logs/SpotWssGate.error.log",
            ...base,
        },
        {
            name: "SpotWssGateV2-TRADE",
            script: "App/public/gate_wss.py",
            args: "--channel=trade",
            out_file: "/root/WssMiddlewareV2/logs/SpotWssGate.out.log",
            error_file: "/root/WssMiddlewareV2/logs/SpotWssGate.error.log",
            ...base,
        },
        {
            name: "SpotWssGateV2-TICKER",
            script: "App/public/gate_wss.py",
            args: "--channel=ticker",
            out_file: "/root/WssMiddlewareV2/logs/SpotWssGate.out.log",
            error_file: "/root/WssMiddlewareV2/logs/SpotWssGate.error.log",
            ...base,
        },
        // okex
        {
            name: "SpotWssOkexV2-DEPTH",
            script: "App/public/okex_wss.py",
            args: "--channel=depth",
            out_file: "/root/WssMiddlewareV2/logs/SpotWssOkex.out.log",
            error_file: "/root/WssMiddlewareV2/logs/SpotWssOkex.error.log",
            ...base,
        },
        {
            name: "SpotWssOkexV2-KLINE",
            script: "App/public/okex_wss.py",
            args: "--channel=kline",
            out_file: "/root/WssMiddlewareV2/logs/SpotWssOkex.out.log",
            error_file: "/root/WssMiddlewareV2/logs/SpotWssOkex.error.log",
            ...base,
        },
        {
            name: "SpotWssOkexV2-TRADE",
            script: "App/public/okex_wss.py",
            args: "--channel=trade",
            out_file: "/root/WssMiddlewareV2/logs/SpotWssOkex.out.log",
            error_file: "/root/WssMiddlewareV2/logs/SpotWssOkex.error.log",
            ...base,
        },
        {
            name: "SpotWssOkexV2-TICKER",
            script: "App/public/okex_wss.py",
            args: "--channel=ticker",
            out_file: "/root/WssMiddlewareV2/logs/SpotWssOkex.out.log",
            error_file: "/root/WssMiddlewareV2/logs/SpotWssOkex.error.log",
            ...base,
        },
        // lbank
        {
            name: "SpotWssLbkV2-DEPTH",
            script: "App/public/lbk_wss.py",
            args: "--channel=depth",
            out_file: "/root/WssMiddlewareV2/logs/SpotWssLbk.out.log",
            error_file: "/root/WssMiddlewareV2/logs/SpotWssLbk.error.log",
            ...base,
        },
        {
            name: "SpotWssLbkV2-KLINE",
            script: "App/public/lbk_wss.py",
            args: "--channel=kline",
            out_file: "/root/WssMiddlewareV2/logs/SpotWssLbk.out.log",
            error_file: "/root/WssMiddlewareV2/logs/SpotWssLbk.error.log",
            ...base,
        },
        {
            name: "SpotWssLbkV2-TRADE",
            script: "App/public/lbk_wss.py",
            args: "--channel=trade",
            out_file: "/root/WssMiddlewareV2/logs/SpotWssLbk.out.log",
            error_file: "/root/WssMiddlewareV2/logs/SpotWssLbk.error.log",
            ...base,
        },
        {
            name: "SpotWssLbkV2-TICKER",
            script: "App/public/lbk_wss.py",
            args: "--channel=ticker",
            out_file: "/root/WssMiddlewareV2/logs/SpotWssLbk.out.log",
            error_file: "/root/WssMiddlewareV2/logs/SpotWssLbk.error.log",
            ...base,
        },
    ]
}
